2021-08-20 16:30:12,925 - Log.py->info[line:96] -             INFO: 4dExplorer is launched.
2021-08-20 16:30:43,191 - Log.py->error[line:114] -             ERROR: 0
Traceback (most recent call last):
  File "e:/4D_STEM_UI_5/app.py", line 145, in <module>
    sys.exit(app.exec_())
SystemExit: 0

2021-08-20 16:33:07,650 - Log.py->info[line:96] -             INFO: 4dExplorer is launched.
2021-08-20 16:33:09,169 - Log.py->info[line:96] -             INFO: System Exit: 4dExplorer is closed
